import { Injectable } from "@angular/core";
import { Product } from "./product.model";
import { Observable } from "rxjs";
import { from } from "rxjs";

@Injectable()
export class StaticDataSource {
	private products: Product[] = [
		new Product(1, "Autumn salad", "vegetarian", "This salad is screaming fall.  And lets hope that it eventually brings cooler weather with it.", ["In a large bowl combine romaine, pear, apple, bacon, cranberries, pecans and feta cheese. Toss.", "To make the creamy poppyseed dressing: Whisk together mayonnaise, milk, sugar, cider vinegar, and poppyseeds. Add desired amount to the salad and toss."], ["4 cups romaine lettuce, chopped", "1 barlett pear, diced", "1 red apple, diced (I used gala)", "5 thick sliced bacon, cooked and chopped", "1/4 cup dried cranberries", "1/4 cup pecans, chopped", "1/4 cup feta cheese", "1/4 Creamy Poppyseed Dressing", "1/4 cup mayonnaise", "1/4 cup 2% milk", "3 tablespoons sugar", "4 teaspoons cider vinegar", "2 teaspoons poppy seeds"], "30m", 3),
		
		new Product(2, "Ratatouille", "vegetarian", "Ratatouille is one of the more known classic French dishes. And it’s the perfect example of a dish that is truly way grander than the sum of its ingredients. ", ["Place eggplant pieces in colander over your sink. Sprinkle with salt. Leave for 20 minutes as eggplant sweats out its bitterness. Pat dry. In a large heavy pot or Dutch Oven like this one, heat 2 tbsp extra virgin olive oil over medium heat until shimmering but not smoking. Add onions. Cook, stirring regularly, until translucent (about 5 minutes). Now add red peppers and green peppers, cook for another 4 minutes, and continue to stir.", "Add garlic, tomatoes, zucchini, eggplant, wine, and fresh thyme springs. Stir in black pepper, paprika, rosemary. Season with kosher salt. Raise heat to medium-high and bring to a boil for 5 minutes, stirring once of twice. Turn heat down, cover and cook over low heat for 20 minutes or so.", "Remove ratatouille from heat. Taste and adjust salt to your liking. Add sherry vinegar and a generous drizzle of Private Reserve EVOO. Top with fresh basil.", "To serve, transfer ratatouille to dinner bowls, top each with a fried egg (sunny-side up) and add crusty bread on the side."], ["1 lb eggplant, peeled (or part-peeled in striped pattern), and cut into 1-inch pieces", "Kosher salt", "Private Reserve Greek extra virgin olive oil", "1 medium-sized yellow onion, finely chopped", "1 red bell pepper, stemmed, seeded, and cut into 1-inch pieces", "1 green bell pepper, stemmed, seeded, and cut into 1-inch pieces", "6 garlic cloves, peeled, and minced", "2 lb vine ripe tomatoes, chopped", "2 zucchini, halved length-wise, then cut into 1/2 inch pieces (half moons)", "1/2 cup red wine", "2 springs fresh thyme", "1 tsp black pepper", "1 tsp sweet paprika", "1 tsp dried rosemary", "1 tbsp sherry vinegar", "3 tbsp chopped fresh basil"], "1h 30m", 4),
		
		
		new Product(4, "French toasts", "breakfasts", "Learn how to make French toast in just 10 minutes! Add the sweet flavors of vanilla and cinnamon to your breakfast with our delicious French toast recipe.", ["Cut the challah bread into 2.5cm thick slices. Allow to sit out for a while to dry out.", "Heat the griddle to 180C. Lightly brush with a butter-soaked piece of paper towel.", "Combine the eggs, double cream, orange zest (reserving 3 tbsp orange zest for Orange bourbon butter), juice, cinnamon and ground nutmeg in a shallow wide dish.", "Dip the slices of bread into the egg mixture allowing them to soak on both sides. Transfer each piece to the hot griddle and cook until golden brown on both sides, about 3 minutes per side. Try to flip only once. Serve with Orange bourbon butter."], ["1 loaf challah bread", "Melted butter, to oil griddle", "6 eggs", "125ml double cream", "1 orange, zested and juiced", "1/4 tsp ground cinnamon", "1/4 tsp fresh ground nutmeg"], "20m", 3),
		
		new Product(7, "Mac and cheese", "main", "This is a nice rich mac and cheese. Serve with a salad for a great meatless dinner. Hope you enjoy it.", ["Cook macaroni according to the package directions. Drain.", "In a saucepan, melt butter or margarine over medium heat. Stir in enough flour to make a roux. Add milk to roux slowly, stirring constantly. Stir in cheeses, and cook over low heat until cheese is melted and the sauce is a little thick. Put macaroni in large casserole dish, and pour sauce over macaroni. Stir well.", "Melt butter or margarine in a skillet over medium heat. Add breadcrumbs and brown. Spread over the macaroni and cheese to cover. Sprinkle with a little paprika.", "Bake at 350 degrees F (175 degrees C) for 30 minutes. Serve."], ["8 ounces uncooked elbow macaroni", "2 cups shredded sharp Cheddar cheese", "1/2 cup grated Parmesan cheese", "3 cups milk", "1/4 cup butter", "2 1/2 tablespoons all-purpose flour", "2 tablespoons butter", "1/2 cup bread crumbs", "1 pinch paprika"], "50m", 5),
		
		new Product(8, "Ceviche", "main", "No cooking required, this Easy Shrimp Ceviche recipe is the best dish for summer. Cool, light and refreshing, easy Shrimp Ceviche is on the table in minutes and perfect for parties. ", ["Chop the shrimp into 1/2 inch pieces and transfer to a bowl. Set aside.", "In a small bowl, whisk together the lemon, lime and orange juice to combine. Pour 1/2 cup of the citrus juice over the shrimp and toss to combine. Allow the shrimp to marinade in the juice for 15 minutes.", "Add the tomato, jalapeño, jicama (or apple), cilantro and red onion to the shrimp. Toss the ingredients to combine and allow to marinade for an additional 10 minutes. Stir in the avocado and remaining juices.", "Season the ceviche with salt and pepper, to taste. Serve immediately with tortilla chips, if desired."], ["1 lb cooked shrimp, peeled and deveined", "1/4 cup fresh lemon juice, about two lemons", "1/4 cup fresh lime juice, about 3 limes", "1/2 cup fresh squeezed orange juice", "4 whole plum tomatoes, seeds removed and diced", "2 whole jalapeno peppers, seeds and vein removed, minced", "1 cup diced jicama (or diced peeled apple)", "1/2 cup chopped fresh cilantro", "1/4 cup finely chopped red onion", "1 avocado, pitted and diced", "kosher salt and fresh ground pepper"], "40m", 4),
		
		
		new Product(10, "Taco Casserole", "meat_and_fish", "I thought the in-game item looked pretty tasty, so I decided to take a shot at making a real-life version! The best part about this particular recipe is that it is very customizable.", ["Preheat oven to 350°F", "Cook rice according to package directions. Set aside.", "Brown beef (or turkey) in a medium skillet.", "Once the meat has been thoroughly browned stir in cooked rice, enchilada sauce, and spices until well mixed, transfer mixture to a greased casserole dish, top with shredded cheese, bake for 20 minutes", "Once done top with sliced olives, diced tomato, chopped green onions, and sour cream", "Optional add-ins: crushed tortilla chips, salsa, guacamole, shredded lettuce… or come up with your own!"], ["1 lb ground beef or ground turkey", "1 cup uncooked rice", "1 can enchilada sauce", "1 pinch salt", "1 pinch ground black pepper", "1 tsp chili powder", "1 tsp ground cumin", "1/2 tsp garlic powder", "1/2 tsp onion powder", "1.5 cups shredded cheddar or colby jack cheese", "1 can sliced black olives", "1 tomato, diced", "1/4 cup chopped green onions", "1 cup sour cream"], "1h 30m", 4),

		new Product(11, "Chilli con carne", "meat_and_fish", "Jo Pratt’s spicy chilli con carne is a one-pot wonder: easy to throw together using mostly storecupboard ingredients.", ["Heat the oil in a large, heavy-based saucepan with a lid and fry the onion and garlic until softened. Increase the heat and add the mince, cooking quickly until browned and breaking down any chunks of meat with a wooden spoon.", "Pour in the red wine and boil for 2–3 minutes.", "Stir in the tinned tomatoes, tomato purée, fresh chilli or chilli flakes, cumin, coriander, cinnamon, and Worcestershire sauce and crumble in the stock cube. Season well with salt and freshly ground black pepper. Bring to a simmer, cover with a lid and cook over a gentle heat for about 50 minutes to 1 hour, stirring occasionally until the mixture is rich and thickened.", "Add the kidney beans and fresh coriander. Cook for a further 10 minutes, uncovered, before removing from the heat, adding any extra seasoning if necessary. Serve with rice, guacamole, sour cream and a big green salad."], ["2 tbsp olive oil", "2 onions, chopped", "2 garlic cloves, crushed", "1kg/2¼lb lean beef mince", "250ml/9fl oz red wine", "2 x 400g cans chopped tomatoes", "3 tbsp tomato purée", "2 red chillies, thinly sliced, or 3–4 tsp dried chilli flakes", "1 tsp ground cumin", "1 tsp ground coriander", "1 stick cinnamon", "good shake of Worcestershire sauce", "1 beef stock cube", "2 x 400g can red kidney beans, rinsed and drained", "1 large bunch coriander leaves, roughly chopped", "salt and freshly ground black pepper", "wedges of lime, to serve"], "1h 10m", 5),
		
		new Product(12, "Pumpkin pie", "desserts", "This is the traditional holiday pumpkin pie. This pie is easy to prepare and even easier to enjoy. Just mix, pour, bake for a delicious homemade tradition.", ["Mix sugar, cinnamon, salt, ginger and cloves in small bowl. Beat eggs in large bowl. Stir in pumpkin and sugar-spice mixture. Gradually stir in evaporated milk.", "Pour into pie shell.", "Bake in preheated 425° F oven for 15 minutes. Reduce temperature to 350° F; bake for 40 to 50 minutes or until knife inserted near center comes out clean. Cool on wire rack for 2 hours. Serve immediately or refrigerate. Top with whipped cream before serving."], ["3/4 cup granulated sugar", "1 teaspoon ground cinnamon", "1/2 teaspoon salt", "1/2 teaspoon ground ginger", "1/4 teaspoon ground cloves", "2 large eggs", "1 can (15 oz.) LIBBY'S® 100% Pure Pumpkin", "1 can (12 fl. oz.) NESTLÉ® CARNATION® Evaporated Milk", "1 unbaked 9-inch (4-cup volume) deep-dish pie shell", "Whipped cream (optional)"], "2h", 5),
		
		new Product(13, "Key Lime Pie", "desserts", "This recipe uses condensed milk and sour cream. Fabulously easy. . . a summertime favorite! If you have time, a homemade graham cracker crust is better! ", ["Preheat oven to 350 degrees F (175 degrees C).", "In a medium bowl, combine condensed milk, sour cream, lime juice, and lime rind. Mix well and pour into graham cracker crust.", "Bake in preheated oven for 5 to 8 minutes, until tiny pinhole bubbles burst on the surface of pie. DO NOT BROWN! Chill pie thoroughly before serving. Garnish with lime slices and whipped cream if desired."], ["1 (9 inch) prepared graham cracker crust", "3 cups sweetened condensed milk", "1/2 cup sour cream", "3/4 cup key lime juice", "1 tablespoon grated lime zest"], "1h 40m", 5),
		
	];
	getProducts(): Observable<Product[]> {
		return from([this.products]);
	}
}